name: artifact
on: 
  push: 
    branches: [main]
    
  pull_request:
    types: [opened,closed,edited,synchronize]
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: pull code
        uses: actions/checkout@v7
      - name: node
        uses: actions/setup-node@v6.5.0
        with: 
          node-version: '20'
      - name: dep
        run: npm ci
      - name: lint
        run: npm run lint
      - name: test
        run: npm run test
  build:
    outputs:
      file_name: ${{ steps.publish.outputs.x }}
    needs: [test]
    runs-on: ubuntu-22.04
    steps:
     - name: pull code
       uses: actions/checkout@v7
     - name: node
       uses: actions/setup-node@v6.5.0
       with: 
          node-version: '20'
     - name: dep
       run: npm ci
     - name: build
       run: npm run build
     - name: upload artifact 
       uses: actions/upload-artifact@v7
       with:
         name: dist-artifact
         path: |
           dist
     - name: file_name_output
       id: publish
       run: find dist/assets/*.js -type f execdir ehco 'x={}' >> $GITHUB_OUTPUT  ';'
  deploy:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
     - name: pull code
       uses: actions/checkout@v7
     - name: node
       uses: actions/setup-node@v6.5.0
       with: 
          node-version: '20'
     - name: dep
       run: npm ci
     - name: dwonload artifact
       uses: actions/download-artifact@v7
       with:
         name: dist-artifact
         path: ./dist
     - name: show artifact
       run: |
         cd ./dist
         ls
     - name: access file name
       run: ${{needs.build.outputs.file_name}}
     - name: deploy
       run: echo "Deploying done ..."
