name: artifact
on: 
  push: 
    branches: [main]
    paths-ignore: '.github/**'
  pull_request:
    types: [opened,closed,edited,synchronize]
    
jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
      - name: pull code
        uses: actions/checkout@v7
      - name: node
        uses: actions/setup-node@v6.5.0
        with: 
          node-version: '20'
      - name: dep
        run: npm ci
      - name: lint
        run: npm lint
      - name: test
        run: npm test
  build:
    needs: [test]
    runs-on: ubuntu-22.04
    steps:
     - name: pull code
       uses: actions/checkout@v7
     - name: node
       uses: actions/setup-node@v6.5.0
       with: 
          node-version: '20'
     - name: dep
       run: npm ci
     - name: build
       run: npm build
  deploy:
    runs-on: ubuntu-22.04
    needs: [build]
    steps:
     - name: pull code
       uses: actions/checkout@v7
     - name: node
       uses: actions/setup-node@v6.5.0
       with: 
          node-version: '20'
     - name: dep
       run: npm ci
     - name: deploy
       run: echo "Deploying done ..."
