name: demo
on: 
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened,edited,closed,synchronize]
    branches: main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: node
        uses: actions/setup-node@v7
        with:
           node-version: '20'
           cache: 'npm'
      - name: cacheing
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: xx-${{hashFiles('**/package-lock.json')}}
      - name: dep
        run: npm install
      - run: npm run lint
      - run: npm test
  build:
    needs: [test]
    runs-on: ubuntu-22.04
    outputs:
      x: ${{steps.print_outputout.outputs.k}}
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: node
        uses: actions/setup-node@v7
        with:
           node-version: '20'
           cache: 'npm'
      - name: cacheing
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: xx-${{hashFiles('**/package-lock.json')}}
      - name: dep
        run: npm install
      - run: npm build
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist_zip
          path: dist
      - name: output
        id: print_outputout
        run: find  dist/assets/**.js -type f -exec echo 'k={}' >> $GITHUB_OUTPUT ';'
  deploy:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v7
      - name: node
        uses: actions/setup-node@v7
        with:
           node-version: '20'
           cache: 'npm'
      - name: cacheing
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: xx-${{hashFiles('**/package-lock.json')}}
      - name: dep
        run: npm install
      - name: download output
        uses: actions/download-artifact@v7
        with:
          name: dist_zip
          path: ./dist
      - name: check
        run: |
          cd ./dist
          ls
      - name: take output
        run: echo "${{needs.build.outputs.x}}"
      - run: echo "deploy"
      
      
